<script lang="ts">
  import { Response } from "$lib/components/ai-elements/response/index.js";
  import { onMount } from "svelte";

  const tokens = [
    "### Hello",
    " World",
    "\n\n",
    "This",
    " is",
    " a",
    " **mark",
    "down",
    "**",
    " response",
    " from",
    " an",
    " AI",
    " model",
    ".",
    "\n\n",
    "---",
    "\n\n",
    "## Tables",
    "\n\n",
    "| Column 1",
    " | Column 2",
    " | Column 3",
    " |",
    "\n",
    "|----------|----------|----------|",
    "\n",
    "| Row 1, Col 1",
    " | Row 1, Col 2",
    " | Row 1, Col 3",
    " |",
    "\n",
    "| Row 2, Col 1",
    " | Row 2, Col 2",
    " | Row 2, Col 3",
    " |",
    "\n",
    "| Row 3, Col 1",
    " | Row 3, Col 2",
    " | Row 3, Col 3",
    " |",
    "\n\n",
    "## Blockquotes",
    "\n\n",
    "> This",
    " is",
    " a",
    " blockquote.",
    " It",
    " can",
    " contain",
    " multiple",
    " lines",
    " and",
    " **formatted**",
    " text.",
    "\n",
    ">",
    "\n",
    "> It",
    " can",
    " even",
    " have",
    " multiple",
    " paragraphs.",
    "\n\n",
    "## Inline",
    " Code",
    "\n\n",
    "Here",
    " is",
    " some",
    " text",
    " with",
    " `inline",
    " code`",
    " in",
    " the",
    " middle",
    " of",
    " a",
    " sentence.",
    " You",
    " can",
    " also",
    " use",
    " `const",
    " x",
    " =",
    " 42`",
    " for",
    " variable",
    " declarations.",
    "\n\n",
    "## Code",
    " Blocks",
    "\n\n",
    "```",
    "javascript",
    "\n",
    "const",
    " greeting",
    " = ",
    "'Hello, world!'",
    ";",
    "\n",
    "console",
    ".",
    "log",
    "(",
    "greeting",
    ")",
    ";",
    "\n",
    "```",
    "\n\n",
    "## Math",
    "\n\n",
    "It",
    " also",
    " supports",
    " math",
    " equations",
    ", ",
    "like",
    " this",
    " inline",
    " one",
    ": ",
    "$",
    "E",
    " = ",
    "mc",
    "^2",
    "$",
    ".",
    "\n\n",
    "And",
    " here",
    " is",
    " a",
    " display",
    " equation",
    " for",
    " the",
    " quadratic",
    " formula",
    ":",
    "\n\n",
    "$$",
    "\n",
    "x",
    " = ",
    "\\frac",
    "{",
    "-b",
    " \\pm",
    " \\sqrt",
    "{",
    "b^2",
    " -",
    " 4ac",
    "}",
    "}",
    "{",
    "2a",
    "}",
    "\n",
    "$$",
    "\n\n",
    "## Links",
    " and",
    " Lists",
    "\n\n",
    "Here's",
    " a",
    " [",
    "link",
    "](",
    "https://example.com",
    ")",
    " and",
    " some",
    " more",
    " text",
    " with",
    " an",
    " unordered",
    " list",
    ":",
    "\n\n",
    "-",
    " Item",
    " one",
    "\n",
    "-",
    " Item",
    " two",
    "\n",
    "-",
    " Item",
    " three",
    "\n\n",
    "## Ordered",
    " Lists",
    "\n\n",
    "1.",
    " First",
    " item",
    "\n",
    "2.",
    " Second",
    " item",
    "\n",
    "3.",
    " Third",
    " item",
  ];

  let content = $state("");
  let isStreaming = $state(false);
  let isLastMessage = $state(false);

  onMount(() => {
    let currentContent = "";
    let index = 0;

    const interval = setInterval(() => {
      if (index < tokens.length) {
        isStreaming = true;
        currentContent += tokens[index];
        content = currentContent;
        if (index === tokens.length - 1) {
          isLastMessage = true;
        }
        index++;
      } else {
        clearInterval(interval);
        isStreaming = false;
        isLastMessage = false;
      }
    }, 100);

    return () => clearInterval(interval);
  });
</script>

<div
  class="m-6 border rounded-xl p-6 shadow-md overflow-y-auto max-h-[80vh] dark-scrollbar min-h-[80vh]"
>
  <Response {content} animation={{enabled: isStreaming  }} />
</div>
